# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: aa376a50a909a5a2d409dd2916ff2359159324bb7ecf3a306fe8bb2e71fd8ff0372c9977764d80e339bfc58112554f52b2e73e4b976b6636af3abfed00e30298

test:
  secret_key_base: 2836dc263435a857c97d6a1da445d8402210079712535103938858b2d19185f8d4319613fe7c836c0beee4c3b92ca64813ee3919cdc50820271a42382c64a682

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
